env:
  cache-version: v1
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Java 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Cache Bazel files
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ env.cache-version }}-bazel-build-${{ github.sha
          }}
        path: ~/.cache/bazel
        restore-keys: '${{ runner.os }}-${{ env.cache-version }}-bazel-build-

          '
    - continue-on-error: true
      name: Build maven artifacts
      run: bazelisk build //:axt_m2repository
      shell: bash
    - continue-on-error: true
      name: cp to upload dir
      run: 'mkdir -p ~/download

        cp bazel-bin/axt_m2repository.zip ~/download

        '
      shell: bash
    - continue-on-error: true
      name: Upload local snapshot for tests
      uses: actions/upload-artifact@v4
      with:
        name: local-snapshot
        path: ~/download
    - continue-on-error: true
      name: Clean bazel cache
      run: 'rm -rf $(bazel info repository_cache)

        rm -rf ~/.cache/bazel/*/*/external/

        '
      shell: bash
    timeout-minutes: 20
  gradle-emulator-test:
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Java 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Enable KVM group perms
      run: "echo 'KERNEL==\"kvm\", GROUP=\"kvm\", MODE=\"0666\", OPTIONS+=\"static_node=kvm\"\
        ' | sudo tee /etc/udev/rules.d/99-kvm4all.rules\nsudo udevadm control --reload-rules\n\
        sudo udevadm trigger --name-match=kvm       \n"
    - continue-on-error: true
      name: Cache Gradle files
      uses: gradle/gradle-build-action@v3
    - continue-on-error: true
      name: Download local snapshot for tests
      uses: actions/download-artifact@v4
      with:
        name: local-snapshot
        path: ~/download
    - continue-on-error: true
      name: Install to local maven repo
      run: 'mkdir -p ~/.m2

        unzip ~/download/axt_m2repository.zip -d ~/.m2/

        '
      shell: bash
    - continue-on-error: true
      name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - continue-on-error: true
      name: Run gradle tests
      run: 'cd ${{ github.workspace }}/gradle-tests

        ./gradlew nexusOneDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
        --no-watch-fs --stacktrace

        '
      shell: bash
    - continue-on-error: true
      if: success() || failure()
      name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: gradle-tests/**/build/reports/androidTests/
    timeout-minutes: 20
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out repository code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install Java 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Cache Bazel files
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-${{ env.cache-version }}-bazel-test-${{ github.sha }}
        path: ~/.cache/bazel
        restore-keys: '${{ runner.os }}-${{ env.cache-version }}-bazel-test-

          '
    - continue-on-error: true
      name: Run Robolectric tests and fast tagged tests
      run: bazelisk test --test_tag_filters=robolectric,fast --build_tag_filters=robolectric,fast
        --test_output=all ...
      shell: bash
    - continue-on-error: true
      name: Clean bazel cache
      run: 'rm -rf $(bazel info repository_cache)

        rm -rf ~/.cache/bazel/*/*/external/

        '
      shell: bash
    timeout-minutes: 20
name: Build
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
